server:
  port: 8888
spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          #uri: ${HOME}/Desktop/configRepo
          uri: ssh://git@github.com/gdcollectdata/iMakerBot-BackendEnd.git
          default-label: main
          passphrase: 'ahmed'
          clone-on-start: true
          search-paths: imaker-proprietes
      enabled: true
  application:
    name: config-server

